
development:
     adapter: mysql2
     database: my_development
     username: myuser
     password: Avi@2017Yadav
     host: localhost
     
test:
          adapter: mysql2
          database: my_test
          username: myuser
          password: Avi@2017Yadav
          host: localhost

